INSERT INTO category (category_name) VALUES ('American');
INSERT INTO category (category_name) VALUES ('Mexican');
INSERT INTO category (category_name) VALUES ('Italian');
INSERT INTO category (category_name) VALUES ('Fast Food');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Cup');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Pinch');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Ounce');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Each');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Dash');
INSERT INTO unit_of_measure (unit_of_measure_name) VALUES ('Pint');