export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
export const FETCH_ALL_RECIPES_START = 'FETCH_ALL_RECIPES_START';
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';
export const FETCH_ALL_RECIPES_FAIL = 'FETCH_ALL_RECIPES_FAIL';

export const FETCH_SINGLE_RECIPE = 'FETCH_SINGLE_RECIPE';
export const FETCH_SINGLE_RECIPE_START = 'FETCH_SINGLE_RECIPE_START';
export const FETCH_SINGLE_RECIPE_SUCCESS = 'FETCH_SINGLE_RECIPE_SUCCESS';
export const FETCH_SINGLE_RECIPE_FAIL = 'FETCH_SINGLE_RECIPE_FAIL';

export const CHANGE_RECIPE_INPUT = 'CHANGE_RECIPE_INPUT';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SUBMIT_RECIPE = 'SUBMIT_RECIPE';
export const SUBMIT_RECIPE_START = 'SUBMIT_RECIPE_START';
export const SUBMIT_RECIPE_SUCCESS = 'SUBMIT_RECIPE_SUCCESS';
export const SUBMIT_RECIPE_FAIL = 'SUBMIT_RECIPE_FAIL';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CHANGE_INGREDIENT_INPUT = 'CHANGE_INGREDIENT_INPUT';