export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
export const FETCH_ALL_RECIPES_START = 'FETCH_ALL_RECIPES_START';
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';
export const FETCH_ALL_RECIPES_FAIL = 'FETCH_ALL_RECIPES_FAIL';