export const FETCH_ALL_RECIPES = 'FETCH_ALL_RECIPES';
export const FETCH_ALL_RECIPES_START = 'FETCH_ALL_RECIPES_START';
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';
export const FETCH_ALL_RECIPES_FAIL = 'FETCH_ALL_RECIPES_FAIL';

export const FETCH_SINGLE_RECIPE = 'FETCH_SINGLE_RECIPE';
export const FETCH_SINGLE_RECIPE_START = 'FETCH_SINGLE_RECIPE_START';
export const FETCH_SINGLE_RECIPE_SUCCESS = 'FETCH_SINGLE_RECIPE_SUCCESS';
export const FETCH_SINGLE_RECIPE_FAIL = 'FETCH_SINGLE_RECIPE_FAIL';

export const CHANGE_RECIPE_INPUT = 'CHANGE_RECIPE_INPUT';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SUBMIT_RECIPE = 'SUBMIT_RECIPE';
export const SUBMIT_RECIPE_START = 'SUBMIT_RECIPE_START';
export const SUBMIT_RECIPE_SUCCESS = 'SUBMIT_RECIPE_SUCCESS';
export const SUBMIT_RECIPE_FAIL = 'SUBMIT_RECIPE_FAIL';
export const RESET_RECIPE_FORM = 'RESET_RECIPE_FORM';
export const UPDATE_RECIPE_FORM = 'UPDATE_RECIPE_FORM';
export const SUBMIT_RECIPE_UPDATE = 'SUBMIT_RECIPE_UPDATE';
export const SUBMIT_RECIPE_UPDATE_START = 'SUBMIT_RECIPE_UPDATE_START';
export const SUBMIT_RECIPE_UPDATE_SUCCESS = 'SUBMIT_RECIPE_UPDATE_SUCCESS';
export const SUBMIT_RECIPE_UPDATE_FAIL = 'SUBMIT_RECIPE_UPDATE_FAIL';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CHANGE_INGREDIENT_INPUT = 'CHANGE_INGREDIENT_INPUT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const UPDATE_INGREDIENT_FORM = 'UPDATE_INGREDIENT_FORM';

export const CHANGE_COMMENT_INPUT = 'CHANGE_COMMENT_INPUT';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const SUBMIT_COMMENT_START = 'SUBMIT_COMMENT_START';
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const SUBMIT_COMMENT_FAIL = 'SUBMIT_COMMENT_FAIL';

export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';